app/models.py
from typing import List, Optional

import sqlalchemy as sa
from flask_login import UserMixin
from sqlalchemy.orm import Mapped, mapped_column, relationship
from werkzeug.security import check_password_hash, generate_password_hash

from app import db, login

association_table = sa.Table(
    'association_table',
    db.metadata,
    sa.Column('user_id', sa.Integer, sa.ForeignKey('user.id'), primary_key=True),
    sa.Column('section_id', sa.Integer, sa.ForeignKey('section.id'), primary_key=True)
)

class User(UserMixin, db.Model):
    __tablename__ = 'user'
    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(sa.String(32), unique=True, index=True)
    email: Mapped[str] = mapped_column(sa.String(32), unique=True, index=True)
    password_hash: Mapped[Optional[str]] = mapped_column(sa.String(256))

    watching: Mapped[List['Section']] = relationship(
        secondary=association_table,
        back_populates='watchlist'
    )

    def __repr__(self):
        return '<User {}>'.format(self.username)
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
class Section(db.Model):
    __tablename__ = 'section'
    id: Mapped[int] = mapped_column(primary_key=True)
    watchlist: Mapped[List[User]] = relationship(
        secondary=association_table,
        back_populates='watching'
    )

@login.user_loader
def load_user(id):
    return db.session.get(User, int(id))

app/main/forms.py
import sqlalchemy as sa
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, StringField, SubmitField
from wtforms.validators import (DataRequired, Email, EqualTo, Length,
                                ValidationError)

from app import db
from app.models import User


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password_retype = PasswordField('Retype Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Submit')

    def validate_username(self, username):
        user = db.session.scalar(sa.select(User).where(User.username == username.data))
        if user is not None:
            raise ValidationError('Please use a different username.')
        
    def validate_email(self, email):
        user = db.session.scalar(sa.select(User).where(User.email == email.data))
        if user is not None:
            raise ValidationError('Please use a different email address.')

class CourseSearchForm(FlaskForm):
    query = StringField('Search', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

from config import Config
from delta_api import DeltaAPI

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'main.login'
delta_api = DeltaAPI()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)
    
    return app

from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import forms, routes

app/main/routes.py
import sqlalchemy as sa
from flask import flash, redirect, render_template, url_for
from flask_login import current_user, login_required, login_user, logout_user

from app import db, delta_api
from app.main import bp
from app.main.forms import CourseSearchForm, LoginForm, RegistrationForm
from app.models import User


@bp.route('/')
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form = CourseSearchForm()
    if form.validate_on_submit():
        courses = delta_api.search_course(form.query.data)
        return render_template('index.html', courses=courses, form=form)
    return render_template('index.html', form=form)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.scalar(sa.select(User).where(User.username == form.username.data))
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('main.login'))
        login_user(user, remember=form.remember_me.data)
        flash('Successfully logged in as {}'.format(form.username.data))
        return redirect(url_for('main.index'))
    return render_template('login.html', form=form)

@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Successfully registerd {}!'.format(user.username))
        return redirect(url_for('main.index'))

    return render_template('register.html', form=form)

@bp.route('/courses/<course_id>')
def courses(course_id):
    sections = delta_api.get_sections(course_id)
    return render_template('sections.html', sections=sections, section_name=sections[0].course_name if sections else 'Unknown Course')

@bp.route('/courses/<course_id>/sections/<section_id>')
def sections(course_id, section_id):
    section = delta_api.get_section(course_id, section_id)
    return render_template('class.html', section=section)

app/templates/_course.html
<a href="{{ url_for('main.courses', course_id=course.id) }}" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">
            <b>{{ course.subject_id }} {{ course.course_number }}</b>
        </h5>
        <small>{{ course.id }}</small>
    </div>
    <p class="mb-1">{{ course.title }}</p>
</a>

app/templates/_navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Delta Tools</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
        </li>
        {% endif %}      
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/templates/_section.html
<a href="{{ url_for('main.sections', course_id=section.course_id, section_id=section.id) }}" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1">
            {{ section.section_number }} <b>{{ section.course_name }}</b>
        </h5>
        {% if section.is_open() %}
            <span class="badge text-bg-primary rounded-pill">{{ section.open_seats }} of {{ section.total_seats }} seats</span>
        {% else %}
            <span class="badge text-bg-secondary rounded-pill">Full</span>
        {% endif %}
    </div>
    <p class="mb-1">{% if section.instructors %}{{ section.instructors[0] }}{% else %} Not yet assigned. {% endif %}</p>
    <small>{{ section.component }}</small>
</a>

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Index</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  </head>
  <body>
    {% include "_navbar.html" %}
    <div class="container mt-3">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-info" role="alert">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/bootstrap_wtf.html
{% macro form_field(field) %}
    <div class="mb-3">
        {{ field.label(class='form-label') }}
        {{ field(class='form-control' + (' is-invalid' if field.errors else '')) }}
        {%- for error in field.errors %}
            <div class="invalid-feedback">{{ error }}</div>
        {%- endfor %}
    </div>
{% endmacro %}

app/templates/class.html
{% extends "base.html" %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ url_for('main.courses', course_id=section.course_id) }}">{{ section.course_name }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ section.section_number }}</li>
        </ol>
    </nav>

    <h1>{{ section.section_number }} <b>{{ section.course_name }}</b></h1>
    <h2>{{ section.instructors[0] }}</h2><br>
    <p><b>Format:</b> {{ section.component }}</p>
    <p><b>Instructional Mode:</b> {{ section.instruction_mode }}</p>
    <p><b>Campus:</b> {{ section.campus }}</p>
    <p><b>Room:</b> {{ section.building}} {{ section.room }}</p>
    <p><b>Day:</b> {{ section.days }}</p>
    <p><b>Seats Open:</b> {{ section.open_seats }} of {{ section.total_seats }}</p>
{% endblock %}

app/templates/index.html
{% import "bootstrap_wtf.html" as wtf %}
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.query) }}
    <div class="mb-3">
        {{ form.submit(class="btn btn-primary") }}
    </div>
</form>
{% if courses %}
    <p>{{ courses|length }} results</p>
    <div class="list-group">
        {% for course in courses %}
            {% include "_course.html" %}
        {% endfor %}
    </div>
{% endif %}
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Sign In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
    <h1>Register</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}        </p>
        <p>
            {{ form.password_retype.label }}<br>
            {{ form.password_retype(size=32) }}
            {% for error in form.password_retype.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}        </p>
        <p>{{ form.submit() }}</p>
    </form>
</form>
{% endblock %}

app/templates/sections.html
{% extends "base.html" %}

{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ section_name }}</li>
        </ol>
    </nav>

    <h1>Sections</h1>
    <p>{{ sections|length }} results</p>
    <div class="list-group">
        {% for section in sections %}
            {% include "_section.html" %}
        {% endfor %}
    </div>
{% endblock %}